version: '3.9'
services:
  api:
    container_name: api
    build: 
      context: ./api
      target: base
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./api:/workspace:cached
    depends_on:
      - db

  web:
    container_name: web
    build: 
      context: ./web
      target: base
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_SERVER=http://localhost:8080/api
    tty: true
    volumes:
      - ./web:/workspace:cached
    depends_on:
      - api
      
  db:
    build: ./db
    environment:
      - POSTGRES_PASSWORD=Yashi0Takuy@
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    volumes:
      - db-storage:/var/lib/postgresql/data
  
volumes:
  db-storage:
